scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/baeldung
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
resource-server-port: 8080
audience: bff.baeldung.com
          
server:
  ssl:
    enabled: false
logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: INFO
        web: INFO
        
---
spring:
  config:
    activate:
      on-profile: no-auth0
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true
scheme: https

---
spring:
  config:
    activate:
      on-profile: dev
com:
  c4-soft:
    springaddons:
      oidc:
        resourceserver:
          permit-all:
          - /me
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness                
---
spring:
  config:
    activate:
      on-profile: auth0
issuer: https://dev-7g6g7ug82m5ecl4i.us.auth0.com/
username-claim-json-path: $['https://c4-soft.com/user']['name']
authorities-json-path: $['https://c4-soft.com/user']['roles']
audience: bff.baeldung.com
server:
  port: ${resource-server-port}
  ssl:
    enabled: false
  data:
    mongodb:
      uri: mongodb+srv://application_user:O79u71Rlj0FDrNTC@102nationscluster.bezfxm2.mongodb.net/?retryWrites=true&w=majority&appName=102nationscluster
      database: 102nationscluster              
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${issuer}
          username-claim: ${username-claim-json-path}
          authorities:
          - path: ${authorities-json-path}
          aud: ${audience}
        resourceserver:
          permit-all:
          - /api/v1/test
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness
---
spring:
  config:
    activate:
      on-profile: test
issuer: https://dev-7g6g7ug82m5ecl4i.us.auth0.com/
username-claim-json-path: $['https://c4-soft.com/user']['name']
authorities-json-path: $['https://c4-soft.com/user']['roles']
audience: bff.baeldung.com
server:
  port: ${resource-server-port}
  ssl:
    enabled: false
  data:
    mongodb:
      uri: mongodb+srv://application_user:O79u71Rlj0FDrNTC@102nationscluster.bezfxm2.mongodb.net/?retryWrites=true&w=majority&appName=102nationscluster
      database: 102nationscluster          
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${issuer}
          username-claim: ${username-claim-json-path}
          authorities:
          - path: ${authorities-json-path}
          aud: ${audience}
        resourceserver:
          permit-all:
          - /api/v1/test
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness    

                