scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/baeldung
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
resource-server-port: 7084
audience: bff.baeldung.com

server:
  ssl:
    enabled: false

com:
  c4-soft:
    springaddons:
      oidc:
        resourceserver:
          permit-all:
          - /api/v1/me
          - /v3/api-docs/**
          - /swagger-ui/**



logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: INFO
        web: INFO
        

---
spring:
  config:
    activate:
      on-profile: auth0